---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-apps-api
  namespace: preview
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - api.beamery.local
    - beamery.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-site-ng2
  namespace: preview
spec:
  hosts:
  - beamery.local
  gateways:
  - gateway-apps-api
  http:
  - route:
    - destination:
        host: app-site-ng2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-core
  namespace: preview
spec:
  hosts:
  - api.beamery.local
  gateways:
  - gateway-apps-api
  http:
  - match:
    - headers:
        origin:
          exact: "http://beamery.local"
    route:
    - destination:
        host: api-core

###########################################
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: elasticsearch
  namespace: preview
spec:
  hosts:
  - elasticsearch.elasticsearch.svc.cluster.local
  gateways:
  - mesh
  http:
  - route:
    - destination:
        host: elasticsearch.elasticsearch.svc.cluster.local
  tcp:
  - route:
    - destination:
        host: elasticsearch.elasticsearch.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis
  namespace: preview
spec:
  hosts:
  - redis-cluster.redis.svc.cluster.local
  gateways:
  - mesh
  tcp:
  - route:
    - destination:
        host: redis-cluster.redis.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mongodb
  namespace: preview
spec:
  hosts:
  - mongodb.mongodb.svc.cluster.local
  gateways:
  - mesh
  tcp:
  - route:
    - destination:
        host: mongodb.mongodb.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rabbitmq
  namespace: preview
spec:
  hosts:
  - rabbitmq.rabbitmq.svc.cluster.local
  gateways:
  - mesh
  http:
  - route:
    - destination:
        host: rabbitmq.rabbitmq.svc.cluster.local
  tcp:
  - route:
    - destination:
        host: rabbitmq.rabbitmq.svc.cluster.local
