---
apiVersion: v1
kind: Service
metadata:
  name: istio-pilot
  namespace: {{.istio.namespace}}
  labels:
    istio: pilot
spec:
  ports:
  - port: 15003
    name: http-old-discovery
  - port: 15005
    name: https-discovery
  - port: 15007
    name: http-discovery
  - port: 15010
    name: grpc-xds
  - port: 15011
    name: https-xds
  - port: 8080
    name: http-legacy-discovery
  - port: 9093
    name: http-monitoring
  selector:
    istio: pilot
---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingress
  namespace: {{.istio.namespace}}
  labels:
    istio: ingress
spec:
  type: LoadBalancer
  # externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    istio: ingress
---
apiVersion: v1
kind: Service
metadata:
  name: istio-sidecar-injector
  namespace: {{.istio.namespace}}
  labels:
    istio: sidecar-injector
spec:
  ports:
  - port: 443
  selector:
    istio: sidecar-injector
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: istio-pilot
#   namespace: {{.istio.namespace}}
#   labels:
#     istio: pilot
# spec:
#   ports:
#     - name: http-apiserver
#       port: 8081
#     - name: http-discovery
#       port: 8080
#   selector:
#     istio: pilot
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: istio-ingress
#   namespace: {{.istio.namespace}}
#   labels:
#     istio: ingress
# spec:
#   externalTrafficPolicy: Local
#   ports:
#     - name: http
#       port: 80
#     - name: https
#       port: 443
#   selector:
#     istio: ingress
#   type: LoadBalancer
# ---
