---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-pilot
  namespace: {{.istio.namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-mixer
  namespace: {{.istio.namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-citadell
  namespace: {{.istio.namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingress
  namespace: {{.istio.namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-egress
  namespace: {{.istio.namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-sidecar
  namespace: {{.istio.namespace}}
