{{.templatepreamble}}
kind: Service
apiVersion: v1
metadata:
  name: app-site
  namespace: {{.namespace}}
spec:
  type: NodePort
  selector:
    app: app-site
    type: {{.appsite.type}}
    environment: {{.appsite.environment}}
  ports:
    - protocol: TCP
      port: 9084
      targetPort: 80
      name: app-site
