{{.templatepreamble}}
kind: Service
apiVersion: v1
metadata:
  name: api-notifications
  namespace: {{.namespace}}
spec:
  type: NodePort
  selector:
    app: api-notifications
    type: {{.apinotifications.type}}
    environment: {{.apinotifications.environment}}
  ports:
    - protocol: TCP
      port: 9082
      targetPort: 8000
      name: api-notifications
