---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: istio-test
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: beamery.local
    http:
      paths:
      - path: /.*
        backend:
          serviceName: app-site-ng2
          servicePort: http
  - host: api.beamery.local
    http:
      paths:
      - path: /.*
        backend:
          serviceName: api-core
          servicePort: http
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "beamery.local"
    - "api.beamery.local"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-virtualservice
spec:
  hosts:
  - "beamery.local"
  gateways:
  - istio-gateway
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
