---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: {{.elasticsearch.namespace}}
  labels:
    component: elasticsearch
    role: services
spec:
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
  selector:
    component: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{.elasticsearch.namespace}}
  labels:
    component: elasticsearch
    role: services
spec:
  ports:
  - name: http
    port: 9200
  selector:
    component: elasticsearch
{{- if not .dev }}
    app: es-client
{{- end }}
