---
apiVersion: v1
kind: ReplicationController
metadata:
  name: linkerd-viz
  namespace: {{.linkerd.namespace}}
  labels:
    name: linkerd-viz
spec:
  replicas: 1
  selector:
    name: linkerd-viz
  template:
    metadata:
      labels:
        name: linkerd-viz
    spec:
      containers:
      - name: linkerd-viz
        image: buoyantio/linkerd-viz:0.1.8
        args: ["k8s"]
        imagePullPolicy: Always
        env:
        - name: PUBLIC_PORT
          value: "3000"
        - name: STATS_PORT
          value: "9191"
        - name: SCRAPE_INTERVAL
          value: "30s"
        ports:
        - name: grafana
          containerPort: 3000
        - name: prometheus
          containerPort: 9191
        volumeMounts:
        - name: current-config
          mountPath: /etc/prometheus/prometheus-k8s.yml
          subPath: prometheus-k8s.yml
      - name: kubectl
        # image: buoyantio/kubectl:v1.4.0
        image: buoyantio/kubectl:v1.8.5
        args:
        - "proxy"
        - "-p"
        - "8001"
      volumes:
      - name: current-config
        configMap:
          name: config-linkerd-viz
          items:
          - key: prometheus-k8s.yml
            path: prometheus-k8s.yml

