---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: l5d
  name: l5d
  namespace: linkerd
spec:
  template:
    metadata:
      labels:
        app: l5d
    spec:
      volumes:
      - name: l5d-config
        configMap:
          name: "l5d-config"
      containers:
      - name: l5d
        image: buoyantio/linkerd:1.3.6
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - /io.buoyant/linkerd/config/config.yaml
        ports:
        - name: outgoing
          containerPort: 4140
          hostPort: 4140
        - name: incoming
          containerPort: 4141
        - name: ingress
          containerPort: 4142
        - name: admin
          containerPort: 9990
        volumeMounts:
        - name: "l5d-config"
          mountPath: "/io.buoyant/linkerd/config"
          readOnly: true
      - name: kubectl
        image: buoyantio/kubectl:v1.8.5
        args:
        - "proxy"
        - "-p"
        - "8001"
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: l5d-tcp
  # name: linkerd-tcp
  namespace: linkerd
  labels:
    app: l5d-tcp
    # app: linkerd-tcp
spec:
  template:
    metadata:
      labels:
        app: l5d-tcp
        # app: linkerd-tcp
    spec:
      volumes:
      - name: l5d-tcp-config
        configMap:
          name: "l5d-tcp-config"
      containers:
      - name: linkerd-tcp
        image: linkerd/linkerd-tcp:latest
        args:
        - /io.buoyant/linkerd-tcp/config/config.yaml
        ports:
        - name: admin
          containerPort: 9989
        - name: redis
          containerPort: 7474
        - name: mongodb
          containerPort: 7484
        - name: rabbitmq
          containerPort: 7494
        env:
        - name: RUST_LOG
          value: "trace"
        - name: RUST_BACKTRACE
          value: "1"
        volumeMounts:
        - name: "l5d-tcp-config"
          mountPath: "/io.buoyant/linkerd-tcp/config"
          readOnly: true
      - name: kubectl
        image: buoyantio/kubectl:v1.8.5
        args:
        - "proxy"
        - "-p"
        - "8001"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: namerd
  namespace: linkerd
  labels:
    app: namerd
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: namerd
      labels:
        app: namerd
    spec:
      volumes:
      - name: namerd-config
        configMap:
          name: namerd-config
      containers:
      - name: namerd
        image: buoyantio/namerd:latest
        args:
        - /io.buoyant/namerd/config/config.yaml
        ports:
        - name: thrift
          containerPort: 4100
        - name: http
          containerPort: 4180
        - name: mesh
          containerPort: 4321
        - name: admin
          containerPort: 9991
        volumeMounts:
        - name: namerd-config
          mountPath: "/io.buoyant/namerd/config"
          readOnly: true
      - name: kubectl
        image: buoyantio/kubectl:v1.8.5
        args:
        - "proxy"
        - "-p"
        - "8001"
