---
apiVersion: v1
kind: Service
metadata:
  name: l5d
  namespace: linkerd
spec:
  selector:
    app: l5d
  type: LoadBalancer
  ports:
  - name: ingress
    port: 80
    targetPort: 4142
  - name: incoming
    port: 4141
  - name: admin
    port: 9990
---
apiVersion: v1
kind: Service
metadata:
  name: l5d-tcp
  # name: linkerd-tcp
  namespace: linkerd
spec:
  # clusterIP: None
  type: LoadBalancer
  # type: ClusterIP
  ports:
  - name: admin
    port: 9989
  - name: redis
    port: 7474
  - name: mongodb
    port: 7484
  - name: rabbitmq
    port: 7494
  selector:
    app: l5d-tcp
---
apiVersion: v1
kind: Service
metadata:
  name: namerd
  namespace: linkerd
spec:
  ports:
  - name: thrift
    port: 4100
  - name: http
    port: 4180
  - name: mesh
    port: 4321
  - name: admin
    port: 9991
  selector:
    app: namerd
