{{.templatepreamble}}
kind: Service
apiVersion: v1
metadata:
  name: app-bath
  namespace: {{.namespace}}
spec:
  type: NodePort
  selector:
    app: app-bath
    type: {{.appbath.type}}
    environment: {{.appbath.environment}}
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 80
      name: app-bath
