{{.templatepreamble}}
kind: Service
apiVersion: v1
metadata:
  name: app-site-ng2
  namespace: {{.namespace}}
spec:
  selector:
    app: app-site-ng2
    type: {{.appsiteng2.type}}
    environment: {{.appsiteng2.environment}}
  ports:
  - name: http
    port: 80
