---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-management
  namespace: {{.rabbitmq.namespace}}
  labels:
    app: rabbitmq
spec:
  ports:
  - name: http
    port: 15672
  selector:
    app: rabbitmq
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: {{.rabbitmq.namespace}}
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  ports:
  - name: tcp-amqp
    port: 5672
  - name: tcp-epmd
    port: 4369
  - name: tcp-dist
    port: 25672
  selector:
    app: rabbitmq
