---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cerebro
  namespace: {{.elasticsearch.namespace}}
  labels:
    app: cerebro
    component: elasticsearch
    role: tool
data:
  application.conf: |-
    # Secret will be used to sign session cookies, CSRF tokens and for other encryption utilities.
    # It is highly recommended to change this value before running cerebro in production.
    secret = "ki:s:[[@=Ag?QI`W2jMwkY:eqvrJ]JqoJyi2axj3ZvOv^/KavOT4ViJSv?6YY4[N"

    # Application base path
    basePath = "/"

    # Defaults to RUNNING_PID at the root directory of the app.
    # To avoid creating a PID file set this value to /dev/null
    pidfile.path=/dev/null

    # Rest request history max size per user
    rest.history.size = 50

    # Path of local database file
    data.path = "./cerebro.db"

    es = {
      gzip = true
    }

    # Authentication
    auth = {
    }
    hosts = [
      {
{{- if not .dev }}
        host = "https://elasticsearch:9200"
        name = "Elasticsearch_{{.elasticsearch._env}}_{{.elasticsearch._region}}"
{{- else }}
        host = "http://elasticsearch:9200"
        name = "Elasticsearch_dev"
{{- end}}
      }
    ]
    # play.ws.ssl {
    #   trustManaer = {
    #     stores = [
    #       { type = "PEM", path = "/certs/elasticsearch.pem" }
    #     ]
    #   }
    # }
    # play.ws.ssl.loose.acceptAnyCertificate = true
{{- if not .dev }}
    play.ws.ssl {
      trustManaer = {
        stores = [
          { type = "JKS", path = "/certs/keystore.jks" }
        ]
      }
      loose = {
        acceptAnyCertificate = true
      }
    }
{{- end}}
