apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cerebro
  namespace: elasticsearch
  labels:
    app: cerebro
    component: elasticsearch
    role: tool
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cerebro
        component: elasticsearch
        role: tool
    spec:
      containers:
      - name: cerebro
        image: "yannart/cerebro"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: cerebro
          mountPath: /opt/cerebro/conf/application.conf
          subPath: application.conf
      volumes:
      - name: cerebro
        configMap:
          name: cerebro
