

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data
  namespace: elasticsearch
  labels:
    app: es-data
    component: elasticsearch
    role: services
spec:
  serviceName: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: es-data
        component: elasticsearch
        role: services
    spec:
      affinity:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: quay.io/pires/docker-elasticsearch:6.2.2
#         resources:
#           requests:
#
#             memory: "512Mi"
#
#
#             cpu: "25m"
#
#           limits:
#
#
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-discovery"
        - name: CLUSTER_NAME
          value: "beamery"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: NODE_INGEST
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Xms512m -Xmx512m"
        - name: ES_PLUGINS_INSTALL
          value: ""
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        - containerPort: 9200
          name: http
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        - name: elasticconfig
          mountPath: /elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: elasticconfig
        configMap:
          name: elasticconfig
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: volume
        component: elasticsearch
        role: services
    spec:
      accessModes:
      - "ReadWriteOnce"
      storageClassName: fast
      resources:
        requests:
          storage: 1Gi
