---
apiVersion: batch/v1
kind: Job
metadata:
  name: es-index
  namespace: elasticsearch
  labels:
    app: es-index
    component: elasticsearch
    role: jobs
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: es-index
        component: elasticsearch
        role: jobs
    spec:
      restartPolicy: Never
      containers:
      - name: es
        image: alpine
        command: ["/bin/sh","-xc","/config/rebuildElasticsearchIndices.sh"]
        env:
        - name: ES_PREFIX
          value: "dev-"
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: config-jobs
          defaultMode: 0766
      - name: podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
