{{.templatepreamble}}
kind: Service
apiVersion: v1
metadata:
  name: app-portal
  namespace: {{.namespace}}
spec:
  type: NodePort
  selector:
    app: app-portal
    type: {{.appportal.type}}
    environment: {{.appportal.environment}}
  ports:
    - protocol: TCP
      port: 9077
      targetPort: 80
      name: app-portal
