{{.templatepreamble}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-mail-as
  namespace: {{.namespace}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: api-mail
  minReplicas: {{.apimail.minreplicas}}
  maxReplicas: {{.apimail.maxreplicas}}
  targetCPUUtilizationPercentage: 100
