---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: redis
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "false"
  labels:
    app: redis-cluster
spec:
  clusterIP: None
  ports:
  - name: client
    port: 6379
  - name: gossip
    port: 16379
  selector:
    app: redis-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: redis
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "false"
  labels:
    app: redis-cluster
spec:
  clusterIP: None
  ports:
  - name: client
    port: 6380
  - name: gossip
    port: 16379
  selector:
    app: redis-cluster
